### ISSUE TITLE
Crash with invalid input (new inventory system introduced in 3688c57aa6b09194351d05bb94dfb3c86bc8f479 )

### ISSUE THREAD

**Issue by VedVid** [VedVid/RAWIG#54]
In inventory, with item sub-menu open, I pressed down arrow. Earlier, I pressed right arrow, and menu closed. Itended behaviour: menu remain open.

```
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
main.(*Creature).InventoryActions(0xc000046140, 0xc000075f70, 0x0, 0x4)
        D:/Programowanie/golang/projects/src/RAWIG/player.go:131 +0x5bd
main.(*Creature).HandleInventory(0xc000046140, 0xc000075f70, 0x0, 0xa)
        D:/Programowanie/golang/projects/src/RAWIG/player.go:115 +0x62
main.(*Creature).InventoryMenu(0xc000046140, 0xc000075f70, 0x462b50)
        D:/Programowanie/golang/projects/src/RAWIG/player.go:92 +0xa6
main.Controls(0xc, 0xc000046140, 0xc000068000, 0x1e, 0x1e, 0xc000075f30, 0x2, 0x2, 0xc000075f70, 0x1000001)
        D:/Programowanie/golang/projects/src/RAWIG/controls.go:48 +0x73
main.main()
        D:/Programowanie/golang/projects/src/RAWIG/main.go:59 +0x61f
Exception 0xc0000005 0x0 0x10 0x7ffef8b66e1e
PC=0x7ffef8b66e1e

runtime: unknown pc 0x7ffef8b66e1e
stack: frame={sp:0x92f4f0, fp:0x0} stack=[0x0,0x92fdf0)
000000000092f3f0:  0000000009a80070  0000000000000001
000000000092f400:  0000000000eb0300  0000000000000000
000000000092f410:  0000000000000190  0000000000000032
000000000092f420:  0000000009ad1c40  00000000026840a0
000000000092f430:  00000000003e0009  0000000000000000
000000000092f440:  0000000009ad1c30  0000000009b11f60
000000000092f450:  0000000000000000  0000000000000001
000000000092f460:  0000000000eb3090  0000000000000006
000000000092f470:  0000000009ad1f60  00007ffef8b65e95
000000000092f480:  0000000000000200  0000000000eb0000
000000000092f490:  0000000000004139  0000000009a80000
000000000092f4a0:  0000000000ef0080  00000000000000c5
000000000092f4b0:  000000000267eca0  000000010000006f
000000000092f4c0:  0000000000000300  0000000000000101
000000000092f4d0:  0000000009b11f60  0000000000004139
000000000092f4e0:  0000000002693c90  00007ffef8bf98a5
000000000092f4f0: <0000000000000000  0000000002677ba0
000000000092f500:  0000000000000430  00000001026e3a50
000000000092f510:  0000000000000000  0000000000000000
000000000092f520:  0000000000000000  0000000000000030
000000000092f530:  0000000000eb30d4  00000000000000c5
000000000092f540:  0000000000000068  0000000000000032
000000000092f550:  0000000002679af0  0000000009ad1c30
000000000092f560:  000000000000001a  0000000005697c60
000000000092f570:  0000000004d3cf40  0000000000000000
000000000092f580:  0000000000000010  0000000077339c6c
000000000092f590:  0000000000000000  000000000000000d
000000000092f5a0:  0000000021000021  0000000000000000
000000000092f5b0:  00000000058a1590  00000000765c5377
000000000092f5c0:  00000000058a1590  0000000000000000
000000000092f5d0:  00000000058a1590  0000000000000000
000000000092f5e0:  0000000069000069  00007ffef64398bc
runtime: unknown pc 0x7ffef8b66e1e
stack: frame={sp:0x92f4f0, fp:0x0} stack=[0x0,0x92fdf0)
000000000092f3f0:  0000000009a80070  0000000000000001
000000000092f400:  0000000000eb0300  0000000000000000
000000000092f410:  0000000000000190  0000000000000032
000000000092f420:  0000000009ad1c40  00000000026840a0
000000000092f430:  00000000003e0009  0000000000000000
000000000092f440:  0000000009ad1c30  0000000009b11f60
000000000092f450:  0000000000000000  0000000000000001
000000000092f460:  0000000000eb3090  0000000000000006
000000000092f470:  0000000009ad1f60  00007ffef8b65e95
000000000092f480:  0000000000000200  0000000000eb0000
000000000092f490:  0000000000004139  0000000009a80000
000000000092f4a0:  0000000000ef0080  00000000000000c5
000000000092f4b0:  000000000267eca0  000000010000006f
000000000092f4c0:  0000000000000300  0000000000000101
000000000092f4d0:  0000000009b11f60  0000000000004139
000000000092f4e0:  0000000002693c90  00007ffef8bf98a5
000000000092f4f0: <0000000000000000  0000000002677ba0
000000000092f500:  0000000000000430  00000001026e3a50
000000000092f510:  0000000000000000  0000000000000000
000000000092f520:  0000000000000000  0000000000000030
000000000092f530:  0000000000eb30d4  00000000000000c5
000000000092f540:  0000000000000068  0000000000000032
000000000092f550:  0000000002679af0  0000000009ad1c30
000000000092f560:  000000000000001a  0000000005697c60
000000000092f570:  0000000004d3cf40  0000000000000000
000000000092f580:  0000000000000010  0000000077339c6c
000000000092f590:  0000000000000000  000000000000000d
000000000092f5a0:  0000000021000021  0000000000000000
000000000092f5b0:  00000000058a1590  00000000765c5377
000000000092f5c0:  00000000058a1590  0000000000000000
000000000092f5d0:  00000000058a1590  0000000000000000
000000000092f5e0:  0000000069000069  00007ffef64398bc

goroutine 1 [running, locked to thread]:
main.(*Creature).InventoryActions(0xc000046140, 0xc000075f70, 0x0, 0x4)
        D:/Programowanie/golang/projects/src/RAWIG/player.go:131 +0x5bd
main.(*Creature).HandleInventory(0xc000046140, 0xc000075f70, 0x0, 0xa)
        D:/Programowanie/golang/projects/src/RAWIG/player.go:115 +0x62
main.(*Creature).InventoryMenu(0xc000046140, 0xc000075f70, 0x462b50)
        D:/Programowanie/golang/projects/src/RAWIG/player.go:92 +0xa6
main.Controls(0xc, 0xc000046140, 0xc000068000, 0x1e, 0x1e, 0xc000075f30, 0x2, 0x2, 0xc000075f70, 0x1000001)
        D:/Programowanie/golang/projects/src/RAWIG/controls.go:48 +0x73
main.main()
        D:/Programowanie/golang/projects/src/RAWIG/main.go:59 +0x61f
rax     0x0
rbx     0x58a1590
rcx     0x13
rdi     0x0
rsi     0x0
rbp     0x58a1590
rsp     0x92f4f0
r8      0x58a1590
r9      0x0
r10     0x1
r11     0x1
r12     0x0
r13     0x5513710
r14     0x5697c60
r15     0x0
rip     0x7ffef8b66e1e
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b
```

**Comment by VedVid** [comment]
```
main.(*Creature).InventoryActions(0xc00003c0a0, 0xc000061f70, 0x0, 0x4)
        D:/Programowanie/golang/projects/src/RAWIG/player.go:131 +0x5bd
                ==  
        chosen := options[KeyToOrder(blt.Read())]
```  
```
main.(*Creature).HandleInventory(0xc00003c0a0, 0xc000061f70, 0x0, 0xa)
        D:/Programowanie/golang/projects/src/RAWIG/player.go:115 +0x62
                ==  
        if option <= len(p.Inventory) { //valid input
	---> turnSpent = p.InventoryActions(o, option) <---
        }
```  
```
main.(*Creature).InventoryMenu(0xc00003c0a0, 0xc000061f70, 0x462b50)
        D:/Programowanie/golang/projects/src/RAWIG/player.go:92 +0xa6  
                ==  
        case blt.TK_I:  
            turnSpent = p.InventoryMenu(o)  
```

**Comment by VedVid** [comment]
Fixed by https://github.com/VedVid/RAWIG/commit/404613a66e714158363c45ae87571fd7ea33fbaf
